spring:
  application:
    name: first-service
    id: first-service

server:
  port: 8081

security:
  basic:
    enabled: true
  user:
    name: arpit
    password: bhargava

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka



